# Generated by Django 4.2.2 on 2023-07-13 01:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pictures')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('service_field', models.CharField(choices=[('Counselling', 'Counselling'), ('Psychology', 'Psychology'), ('Therapy', 'Therapy'), ('Mentorship', 'Mentorship')], default='Counsellor', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Counsellor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pictures')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('course_name', models.CharField(default='course_name', max_length=300)),
                ('student_address', models.CharField(default='student_address', max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellorServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_total', models.IntegerField(default=0)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CounsellorServiceField', to='website.counsellor')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedStudentAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField()),
                ('description', models.TextField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CounsellorApprovedApp', to='website.counsellor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentApprovedApp', to='website.student')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('app_link', models.TextField(blank=True, null=True)),
                ('app_date', models.DateField(blank=True, null=True)),
                ('app_time', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CounsellorApp', to='website.counsellor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentApp', to='website.student')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pictures')),
                ('first_name', models.CharField(default='first_name', max_length=100)),
                ('last_name', models.CharField(default='last_name', max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postcode', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
